### ISSUE TITLE
Wrong gem name

### ISSUE THREAD

**Issue by armcknight** [ianfixes/keepachangelog_manager_gem#3]
Your readme specifies to declare in a Gemfile

```ruby
gem 'keepachangelog'
```

But that is a different gem: https://gitlab.com/basalt/keepachangelog

It should say

```ruby
gem 'keepachangelog_manager'
```

**Comment by ianfixes** [comment]
Well that's embarrassing 🤦‍♂ 

I made the gem before I checked the ruby gem registry, and it looks like I didn't get all of the gem names converted over.
